---
title: "Curso Python3"
author: "José Antonio García Ramirez"
date: "February 7, 2018"
output: 
  md_document:
  variant: markdown_github
---

<code>

[...] Programar: son las cosas que comprendemos tan bien como para enseñarselas a una máquina [...]
                                                     -Knuth
                                                     
´´´
</code>

#Programando en python 3

Prerrequisitos:
  - Conocimientos de un lenguaje compilado o interpretado.
	- Conocimientos con la filosofía POO.

Requerimientos técnicos:
  - Equipos con S.O. Linux.
	- Ambiente Anaconda (jupyter notebook e IDE spider)
	
	
Objetivo:

*Que el asistente identifique la importancia del uso de software libre, y distinga las diferencias entre lenguajes de programación. En especial se le dotará de los conocimientos necesarios, (como declaración de todos los tipos de datos y ciertas estructuras, algoritmos  y paquetes ya implementados en python 3), para que tenga las herramientas suficientes para adentrarse en el ámbito que él decida como: desarrollo web, modelación o cálculo científico*.


##Temario:

  1. Introducción:
    * ¿Por qué usar software libre?
    * ¿Por qué aprender python?
    * ¿Qué es un lenguaje?


  2. Variables, expresiones y sentencias:
    a. Tipos esenciales en python.
    b. Variables y contraste con cuestiones de hardware en C y C++
    c.	Operadores y precedencia.
    d.    _Identitation error_.
    
  3. Funciones:
    a. Llamado de funciones.
    b. Conversión de tipos de datos.
	  c. Conversión por coerción.
	  d. Keyboard input.
	  e. Funciones matemáticas.
	  f. Definición de funciones.

  4. Condicionales y primer ejercicio:
    a. Operador residuo.
	  b. Tipo booleano.
	  c. Operadores and, or y not.
	  d. Uso del condicional if.
    e. *Recursión* 
    
  5. Iteración:
    a. Cadenas.
	  b. Uso de 'for' y 'while'

  6. Módulo string:
    a. Por definir con Ivan..

  7. Listas:
    a. Definición.
    b. Creación.
    c. Acceso a elementos de una lista.
    d. Listas y ciclos for y operadores de listas.
    e. Matrices:
        1. *Numpy* (opcional)
        
  8. Tuplas:
    a. Construcción.
    b.Discusión sobre sus diferencias con otros tipos de datos y lo fácil que es intercambiar el valor de dos variables.
  
  9. El mundo no es determinístico:
    a. Diferencia entre aleatoriedad y semi aleatoriedad.
    b. Crear una lista extensa de números aleatorios.
    c. Calcular la media de la lista anterior.
    d. Calcular la moda de la lista anterior.

10.	Diccionarios.
    a. Construcción y comparación con otros tipos de datos.
    b. Métodos de los diccionarios.
    c. El tipo de dato Long int.


11. Clases I:
    a. POO
    b. Declaración de una clase y diferencia entre atributos de una clase y de un objeto.
    c. Métodos de una clase.

12. Clases II:
    a. Métodos de una clase.
	  b. El constructor __init__() y la palabra reservada self.
	  c. Sobrecarga de operadores.

13.	Clases III:
    a. Herencia.
	  b. Ejercicio 3: Construcción de una clase que simule el espacio euclidiano de dimensión cuatro, con las operaciones usuales definidas en él. Construir a partir de esta clase una subclase que además tenga una función que ejecute el producto de polinomios de grado a lo más tres.

14.	Listas enlazadas:
    a. Construcción de una lista enlazada a partir de objetos 'Nodos'.
	  b. Construcción de una lista como una clase.

15. Pilas:
    a. Definición de Tipo de dato abstracto.
    b. Discusión acerca del código que implementa la estructura Pila en python.

16.	Colas:
    a. Discusión acerca del código que implementa la estructura Cola enlazada en python.
	  b. Análisis de la eficiencia de la implementación anterior en términos de la notación $O(), o()$ y $\theta()$.

17.	Colas de prioridad:
    a. Discusión acerca del código que implementa la estructura Cola de prioridad en python.
    b.Análisis de la eficiencia de la implementación anterior en términos de la notación $O(), o()$ y $\theta()$.


18.	Árboles:
    a. Construcción de un árbol binario.
	  b. Recorridos sobre árboles.

19.	¿Cómo usar python en el desarrollo web?:
    a. Presentación del framework Django y sus características principales.
    b. Más de django

20.	Más allá de la programación:
    a. Presentación y discusión sobre los algoritmos más usados como Dijkstra, Floyd-Warshall, algoritmos greedy, complejidad de Simplex y algoritmos genéticos. 
    b. Breve introducción a la complejidad computacional.

21. *GUI-turtle*
